/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ejercicio2;

import java.awt.Image;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;

/**
 *
 * @author ovall
 */
public class CarreraPiedras extends javax.swing.JFrame implements Runnable{
    Roca r, r2, r3, r4;
    Thread t, t2, t3, t4, t5;
    int x, x2, x3, x4, y, y2, y3, y4;
    String posiciones[];
    /**
     * Creates new form CarreraPiedras
     */
    public CarreraPiedras() {
        initComponents();
        this.setLocationRelativeTo(null);
        posiciones = new String[4];
        x = jLabel1.getX();
        x2 = jLabel2.getX();
        x3 = jLabel3.getX();
        x4 = jLabel4.getX();
        y = jLabel1.getY();
        y2 = jLabel2.getY();
        y3 = jLabel3.getY();
        y4 = jLabel4.getY();
        Image in = new ImageIcon("Caballo.jpg").getImage().getScaledInstance(100, 100, BufferedImage.TYPE_INT_RGB);
        jLabel1.setIcon(new ImageIcon(in));
        jLabel1.setName("Caballo 1");
        Image in2 = new ImageIcon("Caballo2.jpg").getImage().getScaledInstance(100, 100, BufferedImage.TYPE_INT_RGB);
        jLabel2.setIcon(new ImageIcon(in2));
        jLabel2.setName("Caballo 2");
        Image in3 = new ImageIcon("Caballo3.jpg").getImage().getScaledInstance(100, 100, BufferedImage.TYPE_INT_RGB);
        jLabel3.setIcon(new ImageIcon(in3));
        jLabel3.setName("Caballo 3");
        Image in4 = new ImageIcon("Caballo4.jpg").getImage().getScaledInstance(100, 100, BufferedImage.TYPE_INT_RGB);
        jLabel4.setIcon(new ImageIcon(in4));
        jLabel4.setName("Caballo 4");
        r = new Roca(jLabel1, jLabel1.getY(), posiciones);
        r2 = new Roca(jLabel2, jLabel2.getY(), posiciones);
        r3 = new Roca(jLabel3, jLabel3.getY(), posiciones);
        r4 = new Roca(jLabel4, jLabel4.getY(), posiciones);
    }
    
    public void run(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("F1 PIEDRAS");

        jButton1.setText("Iniciar Carrrera");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Reiniciar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(244, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(400, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jButton1.setEnabled(false);
        t5 = new Thread(this);
        t5.start();
        t = new Thread(r);
        t2 = new Thread(r2);
        t3 = new Thread(r3);
        t4 = new Thread(r4);
        t.start();
        t2.start();
        t3.start();
        t4.start();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jButton1.setEnabled(true);
        t.stop();
        t2.stop();
        t3.stop();
        t4.stop();
        jLabel1.setLocation(x, y);
        jLabel2.setLocation(x2, y2);
        jLabel3.setLocation(x3, y3);
        jLabel4.setLocation(x4, y4);
        Image in = new ImageIcon("Caballo.jpg").getImage().getScaledInstance(100, 100, BufferedImage.TYPE_INT_RGB);
        jLabel1.setIcon(new ImageIcon(in));
        Image in2 = new ImageIcon("Caballo2.jpg").getImage().getScaledInstance(100, 100, BufferedImage.TYPE_INT_RGB);
        jLabel2.setIcon(new ImageIcon(in2));
        Image in3 = new ImageIcon("Caballo3.jpg").getImage().getScaledInstance(100, 100, BufferedImage.TYPE_INT_RGB);
        jLabel3.setIcon(new ImageIcon(in3));
        Image in4 = new ImageIcon("Caballo4.jpg").getImage().getScaledInstance(100, 100, BufferedImage.TYPE_INT_RGB);
        jLabel4.setIcon(new ImageIcon(in4));
//        t = new Thread(r);
//        t2 = new Thread(r2);
//        t3 = new Thread(r3);
//        t4 = new Thread(r4);
//        t.start();
//        t2.start();
//        t3.start();
//        t4.start();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarreraPiedras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarreraPiedras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarreraPiedras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarreraPiedras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarreraPiedras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
